site_name: Symbiotic Intelligence - Codex
site_url: https://rickhallett.github.io/symbiotic-intelligence/
docs_dir: docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal # This should give the "minty" feel
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - content.tooltips
  language: en
  icon:
    logo: material/sprout
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - assets/css/custom.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rickhallett/symbiotic-intelligence
    - icon: material/web
      link: https://www.oceanheart.ai
      name: Oceanheart Ltd
  generator: false
plugins:
  - search
  - awesome-pages
nav:
  - Home: index.md
  - The Art of Personal AI: taopa.md